### ISSUE TITLE
Deployment 2020-2.0 checklist

### ISSUE THREAD

**Issue by mrakitin** [NSLS-II-ESM-2/profile_collection#3]
## Previsit 
- [x] Make sure that the current latest environments are pushed to all the bl machines
- [x] Skim the IPython startup files in `profile_collection`
  - Check if it's safe to start `bsui` remotely (does it touch any hardware?) - use `git grep .put` or `git grep caput`
- [x] tested `RE(Eph.move_to(100, grating='600', EPU='105', shutter='open', branch='B'))`
- [x] Check for outstanding PRs and issues on beamline repos
- [x] Check if beamline specific packages pushed to the BL machines
- [ ] (Optional) Enable CI

## Housekeeping 
- [x] Add BL staff to the BL GitHub organization as owners
- [x] Work with BL staff to commit any un-committed changes to their profiles
- [x] Tag the profile as-found as 2019C3.x
- [x] Discuss with BL staff which conda envs they want to keep/delete and perform the cleanup
- [x] Check/update the beamline's inventory with the BL staff (in https://github.com/NSLS-II/playbooks/blob/master/production)

## Test deployment 
- [x] In `~/.bashrc` add the following and remember to `source ~/.bashrc` afterward.
  ```
  export BLUESKY_LOG_FILE=/var/log/bluesky/bluesky.log
  export BLUESKY_IPYTHON_LOG_FILE=/var/log/bluesky/bluesky_ipython.log
  umask 0002
  ```
  and (if needed) create those directories, making them group-read/writeable-able:
      `chown xf21id2:xf21id2 /var/log/bluesky/`
      `chmod g+rws /var/log/bluesky/`
- [x] removed proxies and `path=/opt/conda...` from '~/.bashrc`, replaced with `/etc/profile.d/conda.sh`, `/etc/profile.d/proxy.sh`
- [x] Append to `00-startup.py`  https://gist.github.com/jklynch/a4366b8900ec0c03883403455ae711b2
- [x] Run profile against new environment
  - `BS_ENV=collection-2020-2.0rc7-1 bsui`
    - need `suitcase 0.7.0`: `conda install suitcase=0.7.0`
- [x] Update the profile as needed to run:
  - [x] Replace `.value` -> `.get()` if it's in a `Device`, or with `yield from bps.read()` if in a plan
  - [x] `history.sqlite` issue - see https://blueskyproject.io/bluesky/metadata.html#persistence-between-sessions
  - [ ] potential issue with images in databroker V2
- [x] Run acceptance tests (if any) and run a representative set of scans for the beamline
  - [x] `RE(LEEM_plan(Eph.move_to(100, grating='300', EPU='105', shutter='open', branch='B'))`
  - [x] `RE(LEEM_plan(Eph.move_to(100, grating='300', EPU=None, E_start=110, E_stop=112, E_step=0.5))`
- [x] Tag the updated profile as `2020C2.0`
- [x] Update BSUI via ansible to use the new environment (http://nsls-ii.github.io/deployment/upgrading-beamlines.html#change-bsui-s-default-environment)

**Comment by mrakitin** [comment]
Playbooks update: https://github.com/NSLS-II/playbooks/pull/374.

**Comment by mrakitin** [comment]
xref #8
